create table person
(
    person_id int generated by default as identity primary key,
    name varchar(100) not null unique,
    birth_date int not null check ( birth_date > 1900 and birth_date <= 2022)
);

CREATE TABLE book
(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id int REFERENCES person(id) on delete set null,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL check ( year >= 0 and year <= 2022 )
);

insert into person(name, birth_date)
VALUES ('Иванов Иван Иванович', 1970);
insert into person(name, birth_date)
VALUES ('Петров Петр Петрович', 1999);
insert into person(name, birth_date)
VALUES ('Кириллов Кирилл Кириллович', 1988);

insert into book(name, author, year) VALUES('name','author', 1900);