create table person
(
    person_id int generated by default as identity primary key,
    name varchar(100) not null unique,
    birth_date int not null check ( birth_date > 1900 and birth_date <= 2022)
);

create table book
(
    book_id int generated by default as identity primary key,
    person_id int not null references person(person_id),
    name varchar(200) not null,
    author varchar(100) not null,
    year int check ( year > 0 and year <= 2022 )
);

insert into person(name, birth_date)
VALUES ('Иванов Иван Иванович', 1970);

insert into person(name, birth_date)
VALUES ('Петров Петр Петрович', 1999);

insert into person(name, birth_date)
VALUES ('Кириллов Кирилл Кириллович', 1988);